# Multi-Model Classification Comparison Template
This is a one file classificaiton model comparison template that allows quick comparison of the following models:
* Decision Tree Classification (sds)
* K-Nearest Neighbours (sds)
* Kernel SVM (sds)
* Logistic Regression (sds)
* Naive Bayes (sds)
* Random Forest Classification (sds)
* Support Vector Machines (sds)
* Extremely Randomized Trees (cl)
* Bagging Classifier (cl)
* AdaBoost (cl)
* Gradient Boosting Classifier (cl)

The available metrics that are used for comparison are listed below:
* Accuracy (sds)
* Precision (cl)
* Recall/Sensitivity (cl)
* F1 Score (cl)
* Logloss (cl)
* Specificity (not incorporated yet)

This was setup to allow the user to pass in the path to their .csv file as a string stored in the `path` variable in the **Import the dataset** section below. The template has been setup such that any number of predictor variables can be used, however the response variable **MUST** be the last column in the .csv. 

This model template was adapted from the Super Data Science Machine Learning A-Z Udemy Course Model Selection templates. This template is a combination of all of the classification templates they had (denoted by sds above), and I have added more models and comparison metrics (denoted by cl above).
***

### Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### Importing the dataset

In [2]:
path = 'step4_data.csv'
dataset = pd.read_csv(path)
cols = dataset.columns.tolist()
cols.remove('NRCan')
cols.append('NRCan')
dataset = dataset[cols]
dataset = dataset.iloc[:,2:]
dataset = dataset.fillna(0)
dataset['NRCan'] = dataset['NRCan'].apply(lambda x: int(x[0]))
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

### Splitting the dataset into the Training set and Test set

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [5]:
models = ['decision_tree', 'knn', 'kernel_svm', 'logistic_regression', 'naive_bayse', 'random_forest', 'svm', 'extremely_random_trees', 'bagging', 'adaboost', 'gradientboost']
metrics = ['accuracy', 'precision', 'recall', 'f1_score', 'logloss']
results = pd.DataFrame(index=models, columns=metrics)

***
## Decision Tree Classification

### Training the Decision Tree Classification model on the Training set

In [6]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

### Making the Confusion Matrix

In [7]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, log_loss
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)

# Caclulating and displaying comparison metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
logloss = log_loss(y_true=y_test, y_pred=classifier.predict_proba(X_test))
print("accuracy: "+str(accuracy))
print("precision: "+str(precision))
print("recall: "+str(recall))
print("f1: "+str(f1))
print("logloss: "+str(logloss))

# Storing comparison metrics in dataframe
results.loc['decision_tree', 'accuracy'] = accuracy
results.loc['decision_tree', 'precision'] = precision
results.loc['decision_tree', 'recall'] = recall
results.loc['decision_tree', 'f1_score'] = f1
results.loc['decision_tree', 'logloss'] = logloss

[[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 10  0]
 [ 0  0  0 40]]
accuracy: 1.0
precision: 1.0
recall: 1.0
f1: 1.0
logloss: 3.0830039376129395e-15


***
## K-Nearest Neighbors (K-NN)

### Training the K-NN model on the Training set

In [8]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

### Making the Confusion Matrix

In [9]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, log_loss
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)

# Caclulating and displaying comparison metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
logloss = log_loss(y_true=y_test, y_pred=classifier.predict_proba(X_test))
print("accuracy: "+str(accuracy))
print("precision: "+str(precision))
print("recall: "+str(recall))
print("f1: "+str(f1))
print("logloss: "+str(logloss))

# Storing comparison metrics in dataframe
results.loc['knn', 'accuracy'] = accuracy
results.loc['knn', 'precision'] = precision
results.loc['knn', 'recall'] = recall
results.loc['knn', 'f1_score'] = f1
results.loc['knn', 'logloss'] = logloss

[[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 10  0]
 [ 0  0  0 40]]
accuracy: 1.0
precision: 1.0
recall: 1.0
f1: 1.0
logloss: 0.019150689213021366


***
## Kernel SVM

### Training the Kernel SVM model on the Training set

In [10]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0, probability=True)
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=True, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

## Making the Confusion Matrix

In [11]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, log_loss
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)

# Caclulating and displaying comparison metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
logloss = log_loss(y_true=y_test, y_pred=classifier.predict_proba(X_test))
print("accuracy: "+str(accuracy))
print("precision: "+str(precision))
print("recall: "+str(recall))
print("f1: "+str(f1))
print("logloss: "+str(logloss))

# Storing comparison metrics in dataframe
results.loc['kernel_svm', 'accuracy'] = accuracy
results.loc['kernel_svm', 'precision'] = precision
results.loc['kernel_svm', 'recall'] = recall
results.loc['kernel_svm', 'f1_score'] = f1
results.loc['kernel_svm', 'logloss'] = logloss

[[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0  9  1]
 [ 0  0  0 40]]
accuracy: 0.9846153846153847
precision: 0.9849906191369607
recall: 0.9846153846153847
f1: 0.9843054930774229
logloss: 0.1283960423540199


***
## Logistic Regression

### Training the Logistic Regression model on the Training set

In [12]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

## Making the Confusion Matrix

In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, log_loss
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)

# Caclulating and displaying comparison metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
logloss = log_loss(y_true=y_test, y_pred=classifier.predict_proba(X_test))
print("accuracy: "+str(accuracy))
print("precision: "+str(precision))
print("recall: "+str(recall))
print("f1: "+str(f1))
print("logloss: "+str(logloss))

# Storing comparison metrics in dataframe
results.loc['logistic_regression', 'accuracy'] = accuracy
results.loc['logistic_regression', 'precision'] = precision
results.loc['logistic_regression', 'recall'] = recall
results.loc['logistic_regression', 'f1_score'] = f1
results.loc['logistic_regression', 'logloss'] = logloss

[[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0  9  1]
 [ 0  0  0 40]]
accuracy: 0.9846153846153847
precision: 0.9849906191369607
recall: 0.9846153846153847
f1: 0.9843054930774229
logloss: 0.12163248939752071


***
## Naive Bayes

### Training the Naive Bayes model on the Training set

In [14]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

### Making the Confusion Matrix

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, log_loss
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)

# Caclulating and displaying comparison metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
logloss = log_loss(y_true=y_test, y_pred=classifier.predict_proba(X_test))
print("accuracy: "+str(accuracy))
print("precision: "+str(precision))
print("recall: "+str(recall))
print("f1: "+str(f1))
print("logloss: "+str(logloss))

# Storing comparison metrics in dataframe
results.loc['naive_bayse', 'accuracy'] = accuracy
results.loc['naive_bayse', 'precision'] = precision
results.loc['naive_bayse', 'recall'] = recall
results.loc['naive_bayse', 'f1_score'] = f1
results.loc['naive_bayse', 'logloss'] = logloss

[[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0  9  1]
 [ 0  0  0 40]]
accuracy: 0.9846153846153847
precision: 0.9849906191369607
recall: 0.9846153846153847
f1: 0.9843054930774229
logloss: 0.5313699417109006


***
## Random Forest Classification

### Training the Random Forest Classification model on the Training set

In [16]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 100, criterion = 'gini', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

### Making the Confusion Matrix

In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, log_loss
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)

# Caclulating and displaying comparison metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
logloss = log_loss(y_true=y_test, y_pred=classifier.predict_proba(X_test))
print("accuracy: "+str(accuracy))
print("precision: "+str(precision))
print("recall: "+str(recall))
print("f1: "+str(f1))
print("logloss: "+str(logloss))

# Storing comparison metrics in dataframe
results.loc['random_forest', 'accuracy'] = accuracy
results.loc['random_forest', 'precision'] = precision
results.loc['random_forest', 'recall'] = recall
results.loc['random_forest', 'f1_score'] = f1
results.loc['random_forest', 'logloss'] = logloss

[[ 5  0  0  0]
 [ 2  8  0  0]
 [ 0  0 10  0]
 [ 0  0  0 40]]
accuracy: 0.9692307692307692
precision: 0.978021978021978
recall: 0.9692307692307692
f1: 0.9700854700854701
logloss: 0.0925444984460965


***
## Support Vector Machine (SVM)

### Training the SVM model on the Training set

In [18]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0, probability=True)
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=True, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

### Making the Confusion Matrix

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, log_loss
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)

# Caclulating and displaying comparison metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
logloss = log_loss(y_true=y_test, y_pred=classifier.predict_proba(X_test))
print("accuracy: "+str(accuracy))
print("precision: "+str(precision))
print("recall: "+str(recall))
print("f1: "+str(f1))
print("logloss: "+str(logloss))

# Storing comparison metrics in dataframe
results.loc['svm', 'accuracy'] = accuracy
results.loc['svm', 'precision'] = precision
results.loc['svm', 'recall'] = recall
results.loc['svm', 'f1_score'] = f1
results.loc['svm', 'logloss'] = logloss

[[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0  9  1]
 [ 0  0  0 40]]
accuracy: 0.9846153846153847
precision: 0.9849906191369607
recall: 0.9846153846153847
f1: 0.9843054930774229
logloss: 0.14892696341140402


***
## Extremely Randomized Trees

### Training the Extremely Randomized Tree model on the Training set

In [20]:
from sklearn.ensemble import ExtraTreesClassifier
classifier = ExtraTreesClassifier(n_estimators = 100, criterion = 'gini', random_state = 0)
classifier.fit(X_train, y_train)

ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='auto',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_impurity_split=None,
                     min_samples_leaf=1, min_samples_split=2,
                     min_weight_fraction_leaf=0.0, n_estimators=100,
                     n_jobs=None, oob_score=False, random_state=0, verbose=0,
                     warm_start=False)

### Making the Confusion Matrix

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, log_loss
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)

# Caclulating and displaying comparison metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
logloss = log_loss(y_true=y_test, y_pred=classifier.predict_proba(X_test))
print("accuracy: "+str(accuracy))
print("precision: "+str(precision))
print("recall: "+str(recall))
print("f1: "+str(f1))
print("logloss: "+str(logloss))

# Storing comparison metrics in dataframe
results.loc['extremely_random_trees', 'accuracy'] = accuracy
results.loc['extremely_random_trees', 'precision'] = precision
results.loc['extremely_random_trees', 'recall'] = recall
results.loc['extremely_random_trees', 'f1_score'] = f1
results.loc['extremely_random_trees', 'logloss'] = logloss

[[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 10  0]
 [ 0  0  0 40]]
accuracy: 1.0
precision: 1.0
recall: 1.0
f1: 1.0
logloss: 0.018632875252232426


***
## Bagging Classifier

### Training the Bagging Classifier model on the Training set

In [22]:
from sklearn.ensemble import BaggingClassifier
classifier = BaggingClassifier(n_estimators = 100, random_state = 0)
classifier.fit(X_train, y_train)

BaggingClassifier(base_estimator=None, bootstrap=True, bootstrap_features=False,
                  max_features=1.0, max_samples=1.0, n_estimators=100,
                  n_jobs=None, oob_score=False, random_state=0, verbose=0,
                  warm_start=False)

### Making the Confusion Matrix

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, log_loss
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)

# Caclulating and displaying comparison metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
logloss = log_loss(y_true=y_test, y_pred=classifier.predict_proba(X_test))
print("accuracy: "+str(accuracy))
print("precision: "+str(precision))
print("recall: "+str(recall))
print("f1: "+str(f1))
print("logloss: "+str(logloss))

# Storing comparison metrics in dataframe
results.loc['bagging', 'accuracy'] = accuracy
results.loc['bagging', 'precision'] = precision
results.loc['bagging', 'recall'] = recall
results.loc['bagging', 'f1_score'] = f1
results.loc['bagging', 'logloss'] = logloss

[[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 10  0]
 [ 0  0  1 39]]
accuracy: 0.9846153846153847
precision: 0.986013986013986
recall: 0.9846153846153847
f1: 0.9848843139982382
logloss: 0.052285585821714664


***
## AdaBoost Classifier

### Training the AdaBoost Classifier model on the Training set

In [24]:
from sklearn.ensemble import AdaBoostClassifier
classifier = AdaBoostClassifier(n_estimators = 100, random_state = 0)
classifier.fit(X_train, y_train)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1.0,
                   n_estimators=100, random_state=0)

### Making the Confusion Matrix

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, log_loss
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)

# Caclulating and displaying comparison metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
logloss = log_loss(y_true=y_test, y_pred=classifier.predict_proba(X_test))
print("accuracy: "+str(accuracy))
print("precision: "+str(precision))
print("recall: "+str(recall))
print("f1: "+str(f1))
print("logloss: "+str(logloss))

# Storing comparison metrics in dataframe
results.loc['adaboost', 'accuracy'] = accuracy
results.loc['adaboost', 'precision'] = precision
results.loc['adaboost', 'recall'] = recall
results.loc['adaboost', 'f1_score'] = f1
results.loc['adaboost', 'logloss'] = logloss

[[ 4  1  0  0]
 [ 0 10  0  0]
 [ 0  0  9  1]
 [ 0  0  0 40]]
accuracy: 0.9692307692307692
precision: 0.9710046051509466
recall: 0.9692307692307692
f1: 0.968432477204407
logloss: 0.5907685429166434


***
## Gradient Boosting Classifier

### Training the Gradient Boosting Classifier model on the Training set

In [26]:
from sklearn.ensemble import GradientBoostingClassifier
classifier = GradientBoostingClassifier(n_estimators = 100, loss='deviance', criterion='friedman_mse', random_state = 0)
classifier.fit(X_train, y_train)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=0, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

### Making the Confusion Matrix

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, log_loss
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)

# Caclulating and displaying comparison metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
logloss = log_loss(y_true=y_test, y_pred=classifier.predict_proba(X_test))
print("accuracy: "+str(accuracy))
print("precision: "+str(precision))
print("recall: "+str(recall))
print("f1: "+str(f1))
print("logloss: "+str(logloss))

# Storing comparison metrics in dataframe
results.loc['gradientboost', 'accuracy'] = accuracy
results.loc['gradientboost', 'precision'] = precision
results.loc['gradientboost', 'recall'] = recall
results.loc['gradientboost', 'f1_score'] = f1
results.loc['gradientboost', 'logloss'] = logloss

[[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 10  0]
 [ 0  0  0 40]]
accuracy: 1.0
precision: 1.0
recall: 1.0
f1: 1.0
logloss: 0.0003189946738986487


***
# Summary of Results

In [28]:
results

accuracy precision    recall  f1_score      logloss
decision_tree                  1         1         1         1    3.083e-15
knn                            1         1         1         1    0.0191507
kernel_svm              0.984615  0.984991  0.984615  0.984305     0.128396
logistic_regression     0.984615  0.984991  0.984615  0.984305     0.121632
naive_bayse             0.984615  0.984991  0.984615  0.984305      0.53137
random_forest           0.969231  0.978022  0.969231  0.970085    0.0925445
svm                     0.984615  0.984991  0.984615  0.984305     0.148927
extremely_random_trees         1         1         1         1    0.0186329
bagging                 0.984615  0.986014  0.984615  0.984884    0.0522856
adaboost                0.969231  0.971005  0.969231  0.968432     0.590769
gradientboost                  1         1         1         1  0.000318995

In [29]:
results = results.astype(float)
print('logloss\t     '+results.iloc[:,-1].idxmin())
print(results.iloc[:,:-1].idxmax())

logloss	     decision_tree
accuracy     decision_tree
precision    decision_tree
recall       decision_tree
f1_score     decision_tree
dtype: object
